apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-canary
  namespace: production
  labels:
    app: api-gateway
    version: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
      version: canary
  template:
    metadata:
      labels:
        app: api-gateway
        version: canary
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: api-gateway
        image: ghcr.io/{{ github.repository }}/api-gateway:{{ github.sha }}
        ports:
        - containerPort: 8000
        env:
        - name: VERSION
          value: "canary"
        - name: DEPLOYMENT_TYPE
          value: "canary"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-canary
  namespace: production
  labels:
    app: auth-service
    version: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
      version: canary
  template:
    metadata:
      labels:
        app: auth-service
        version: canary
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: auth-service
        image: ghcr.io/{{ github.repository }}/auth-service:{{ github.sha }}
        ports:
        - containerPort: 8000
        env:
        - name: VERSION
          value: "canary"
        - name: DEPLOYMENT_TYPE
          value: "canary"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-canary
  namespace: production
  labels:
    app: api-gateway
    version: canary
spec:
  selector:
    app: api-gateway
    version: canary
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-canary
  namespace: production
  labels:
    app: auth-service
    version: canary
spec:
  selector:
    app: auth-service
    version: canary
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: api-gateway-destination
  namespace: production
spec:
  host: api-gateway-service
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: auth-service-destination
  namespace: production
spec:
  host: auth-service
  subsets:
  - name: stable
    labels:
      version: stable
  - name: canary
    labels:
      version: canary